name: 'SemRelease'
author: 'Thanh Nguyen <btnguyen2k(at)gmail(dot)com>'
description: 'Publish releases using tags, following sematic versioning'
inputs:
  github-token:
    description: 'GitHub token with access to your repository scoped in as a secret'
    required: true
  dry-run:
    description: 'dry run flag'
    required: false
    default: 'false'
outputs:
  releaseVersion:
    description: 'The release version string'
  releaseNotes:
    description: 'The release notes'
  result:
    description: 'Action result, either ERROR, SKIPPED, or SUCCESS'
runs:
  using: 'node16'
  main: 'dist/index.js'
