name: 'SemRelease'
author: 'Thanh Nguyen <btnguyen2k(at)gmail(dot)com>'
description: 'Publish releases using tags, following sematic versioning'
branding:
  icon: 'git-pull-request'
  color: 'red'
inputs:
  github-token:
    description: 'GitHub token with access to your repository scoped in as a secret'
    required: true
  dry-run:
    description: 'Dry run flag'
    required: false
    default: 'false'
  tag-prefix:
    description: 'Tag prefix, e.g. v'
    required: false
    default: 'v'
  tag-major-release:
    description: 'If set, a major release tag will be created, e.g. v1'
    required: false
    default: 'true'
  tag-minor-release:
    description: 'If set, a minor release tag will be created, e.g. v1.2'
    required: false
    default: 'false'
  auto-mode:
    description: 'If set, next release version is automatically determined, ignoring the information in RELEASE-NOTES or CHANGELOG file'
    required: false
    default: 'false'
  branches:
    description: 'Branches to fetch commit messages for release notes (auto-mode only)'
    required: false
    default: 'main,master'
outputs:
  releaseVersion:
    description: 'The release version string'
  releaseNotes:
    description: 'The release notes'
  result:
    description: 'Action result, either FAILED, SKIPPED, or SUCCESS'
runs:
  using: 'node16'
  main: 'dist/index.js'
