# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Ensure dist/

on:
  workflow_run:
    workflows: [ "units-test" ]
    types: [ "completed" ]

jobs:
  ensure-dist:
    runs-on: ubuntu-latest
    if: |
      (
        (github.event.workflow_run.event == 'pull_request' && github.event.pull_request.merged == true) ||
        github.event.workflow_run.event == 'push'
      ) &&
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        run: npm ci
      - name: Rebuild the dist/ directory
        run: npm run prepare
      - name: Sync dist/ directories
        run: |
          git diff --ignore-space-at-eol dist/
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            echo "Commiting changes to dist/..."
            git config --global user.email "<>"
            git config --global user.name "CI Build"
            git commit -am "build [skip ci]"
            echo "Pushing changes to dist/..."
            git push
          else
            echo "No changes detected after build."
          fi
