# Release new version
name: "release"

on:
  workflow_run:
    workflows: [ "prerelease" ]
    types: [ "completed" ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: SemRelease
        id: semrelease
        uses: ./ # The repo itself is the action, and is always the latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-major-release: true
          tag-minor-release: true
          auto-mode: true
          branches: main,dev
      - name: Cleanup file .semrelease/this_release
        run: |
          RESULT='${{ steps.semrelease.outputs.result }}'
          if [ "${RESULT}" == "SUCCESS" ]; then
            echo "🕘 Cleaning up file .semrelease/this_release..."
            echo > .semrelease/this_release
            git config --global user.email "<>"
            git config --global user.name "CI Build"
            git commit -am "Cleanup file .semrelease/this_release post releasing version ${VERSION}"
            git push -f
          else
            echo "❎ SKIPPED."
          fi
