# Release new version
name: "release"

on:
  workflow_run:
    workflows: [ "Ensure dist/" ]
    types: [ "completed" ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Debug
        run: |
          echo github.event.workflow_run.event: ${{ github.event.workflow_run.event }}
          echo github.event.pull_request.merged: ${{ github.event.pull_request.merged }}
          echo github.event.workflow_run.conclusion: ${{ github.event.workflow_run.conclusion }}
          echo github.ref: ${{ github.ref }}
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: SemRelease
        uses: btnguyen2k/semrelease@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
